### ISSUE TITLE
Responsive grid system

### ISSUE THREAD

**Issue by egoist** [egoist/hack#1]
The current flexbox base grid is not fully responsive yet. 

eg: `-3of12` should take 100% of the width on small-screen devices.

**Comment by net** [comment]
I think 480 is too narrow of a breakpoint. See:

<img width="499" alt="screen shot 2016-07-17 at 11 32 27 pm" src="https://cloud.githubusercontent.com/assets/6983821/16905628/f11dcf9e-4c76-11e6-962a-6f91cae1266b.png">

I (personally) think something closer to 750 would be more idea.

(Also cards need to be styled for the new responsive grid--just remove the style attribute.)

**Comment by egoist** [comment]
@net just used 768px

**Comment by net** [comment]
Looks great! 😀
