### ISSUE TITLE
site-dark.css not found

### ISSUE THREAD

**Issue by franciscotv** [egoist/hack#13]
in the head of sample html files there is a link for a file named: site-dark.css
which is not available in the repo, does that file exists at somebodies computer and forgot to upload it to the github repo?, if not, that <link href="./site-dark.css"> reference should be removed?

Regards.

**Comment by egoist** [comment]
oh, sorry it's still empty so git does not commit it. i think it should be removed for now.

**Comment by egoist** [comment]
maybe i am wrong, can you see https://github.com/egoist/hack/blob/master/src/static/site-dark.css ?

**Comment by franciscotv** [comment]
thanks egoist,
I can see this file:
 hack/src/static/site-dark.css

but is empty.

**Comment by egoist** [comment]
let me know if there's any other issues, closed for now.
