### ISSUE TITLE
Please include actual license file

### ISSUE THREAD

**Issue by criswell** [egoist/hack#15]
I know the README states "MIT" as the license, but that doesn't, actually, place the code under the MIT license. As it stands, in most countries this code would, technically, still be considered copyright the original creator, all rights reserved, and developers who understood this wouldn't use the code because of the potential legal peril.

To rectify this, simply place the MIT license in a file in the repo *or* include the license as a comment in the code.

**Comment by jhabdas** [comment]
FWIW it appears the license [was](https://github.com/egoist/hack/commit/90a9796901432d05223a221e8ebd2545573023f1) in the code. I'm really hoping [0BSD](https://spdx.org/licenses/0BSD.html) helps clean up a lot of these kinds of issues as it does not carry with it the restrictions found in ISC/MIT licenses.

**Comment by jhabdas** [comment]
FWIW it appears the license [was](https://github.com/egoist/hack/commit/90a9796901432d05223a221e8ebd2545573023f1) in the code. I'm really hoping [0BSD](https://spdx.org/licenses/0BSD.html) helps clean up these kinds of misunderstandings as it does not carry with it [the conditions](https://choosealicense.com/licenses/mit/) found in ISC/MIT licenses.

https://tldrlegal.com/license/bsd-0-clause-license

> The BSD 0-clause license goes further than the 2-clause license to allow you unlimited freedom with the software without the requirements to include the copyright notice, license text, or disclaimer in either source or binary forms.  This particular version comes from the Toybox project.
