### ISSUE TITLE
Remove custom scrollbar

### ISSUE THREAD

**Issue by net** [egoist/hack#17]
I think the custom scrollbar should either be removed, or at the very least be optional. I think scrollbars are better as system elements, rather than custom website elements. Users are not used to custom scrollbars, like they are other web elements such as text, buttons, inputs, and alike. A custom scrollbar is jarring and uncomfortable to the user.

I'm not sure about Windows or various Linux flavors, but I think that on OS X the system scrollbar looks far far better than the custom hack scrollbar.

The custom hack scrollbar pushes content to the left, that otherwise would have been flush with the page's edge on a auto-hiding scrollbar.

<img width="110" alt="screen shot 2016-07-19 at 5 17 08 pm" src="https://cloud.githubusercontent.com/assets/6983821/16967132/ab1a188a-4dd5-11e6-9ed7-c2c5c06e9237.png">
<img width="530" alt="screen shot 2016-07-19 at 5 25 18 pm" src="https://cloud.githubusercontent.com/assets/6983821/16967194/df2f2368-4dd5-11e6-9e62-2383043d5f0c.png">

It is not typical for a css framework to include custom scrollbars, especially one so seemingly lightweight as hack.

**Comment by egoist** [comment]
what about the scrollbar for `pre` element? it just looks awful in dark mode.

**Comment by net** [comment]
This?

<img width="486" alt="screen shot 2016-07-19 at 6 45 51 pm" src="https://cloud.githubusercontent.com/assets/6983821/16969190/2015c728-4de1-11e6-98ea-72eeb1255226.png">
