### ISSUE TITLE
Letters collide on a multiline header

### ISSUE THREAD

**Issue by sobolevn** [egoist/hack#19]
It happens with `standard` mode only.

<img width="438" alt="2016-08-04 13 19 21" src="https://cloud.githubusercontent.com/assets/4660275/17398599/43d54514-5a46-11e6-9235-388f387c7cd4.png">

The workaround I have came up with is to set `.standard h1 { line-height: 1em; }`

And the `markdown` mode has these lines:

```css
.hack h1, .hack h2 {
    line-height: 30px;
}
```

Does my workaround seem fine to you? Are there any other tags to be checked and fixed?

I will create a PR with a fix.

**Comment by egoist** [comment]
I prefer something line-height`>= 1.2 and <= 1.5`

you may need to check all the headers, maybe a `word-wrap: break-word` too?

**Comment by sobolevn** [comment]
Yeap, `word-wrap` is totally required.

Without:
<img width="449" alt="2016-08-04 13 49 20" src="https://cloud.githubusercontent.com/assets/4660275/17399354/503b7202-5a4a-11e6-9663-c43b33645935.png">

With:
<img width="386" alt="2016-08-04 13 50 00" src="https://cloud.githubusercontent.com/assets/4660275/17399370/6712af86-5a4a-11e6-9929-7988e7bd2997.png">
