### ISSUE TITLE
Feature requests go here

### ISSUE THREAD

**Issue by egoist** [egoist/hack#2]
Any component/UI/feature request...

- [x] Button
 - [x] Button group
 - [x] Ghost button
- [x] Dark mode

**Comment by pdelanauze** [comment]
dark mode !!

**Comment by egoist** [comment]
@pdelanauze it's in the plan

**Comment by net** [comment]
`<textarea></textarea>` support. Could look something like this.
<img width="444" alt="screen shot 2016-07-17 at 11 10 22 am" src="https://cloud.githubusercontent.com/assets/6983821/16901368/6ae886ba-4c0f-11e6-9c62-be338d0ffd89.png">

**Comment by egoist** [comment]
@net `textarea` is done.

**Comment by net** [comment]
@egoist very nice, it look good to have a partial border of the right too.

Blockquote styling would be nice.

```
> Blockquote here.
> Second line.
```

Another more ambitious feature that would be nice would be a `no-markdown` body class. `no-markdown` would use only traditional styling, with no markdown symbols.

```html
<body class="hack no-markdown">
  <h1>Title</h1>
  <em>Hello, world!</em>
</body>

<!-- Renders (with appropriate styling): -->
Title
Hello, world!
<!-- Instead of: -->
# Title
*Hello, world!*
```

**Comment by egoist** [comment]
@net just remove `.hack` class to exclude markdown css.

**Comment by turshija** [comment]
- [ ] Navigation/menu ?

**Comment by egoist** [comment]
@turshija can you provide a preview or is it something like bootstrap navbar ?

**Comment by turshija** [comment]
Sorry but I have no idea :) Something like bootstrap navbar could be nice.
I wanted to play with this a little bit, and then realised it doesn't have any sort of navigation support ...

**Comment by egoist** [comment]
@pdelanauze there's a demo for dark mode, any suggestion is welcome http://hackcss.com/dark.html

**Comment by Swizz** [comment]
Hi,

I do not know if this is the best place for that ; but what about bower support ?

https://bower.io/docs/creating-packages/

**Comment by net** [comment]
Outlined buttons could look good in dark mode instead of solid.

**Comment by egoist** [comment]
@net maybe a `.btn-ghost` modifier?

@Swizz you can `npm install hack`, that's quite like the bower thing.

**Comment by Swizz** [comment]
@egoist Register/Create bower package is really easy and can be done just with `bower init` with existing npm `package.json` file.
I think we are many to use bower as front end dependencies manager as part of our workflow instead of npm.

But your project : your choices.

**Comment by egoist** [comment]
@Swizz thanks, I know it's easy to work with bower, it will have bower support after this isssue got closed.

**Comment by net** [comment]
I don't know. I feel like ghost buttons just naturally look better in dark mode than the solid ones. I think it should be default for dark mode.

<img width="711" alt="screen shot 2016-07-18 at 11 23 44 am" src="https://cloud.githubusercontent.com/assets/6983821/16920093/4e6b78aa-4cda-11e6-8968-2dbfdce645a2.png">
<img width="682" alt="screen shot 2016-07-18 at 11 24 24 am" src="https://cloud.githubusercontent.com/assets/6983821/16920100/521f3112-4cda-11e6-84a0-d8ba2e775888.png">

**Comment by egoist** [comment]
@net that looks cool

**Comment by egoist** [comment]
@Swizz bower package is published as `hackcss`
