### ISSUE TITLE
Lighten background in dark theme

### ISSUE THREAD

**Issue by hhaslam11** [egoist/hack#21]
Black is a bit too hard on the eyes. I think a dark grey type colour would look a lot nicer

**Comment by egoist** [comment]
It's easy to extend the base theme to something like a dark grey color scheme just like how the [dark theme](https://github.com/egoist/hack/blob/master/src/css/dark.css) did.

You can make a PR if you truly want this happen 😉

**Comment by jhabdas** [comment]
Black is perfect for nighttime reading. Plus it's l33t.
