### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by tiaanduplessis** [egoist/hack#24]
How about also adding solorized and solorized dark themes? Will be happy to work on it.

**Comment by egoist** [comment]
Please do 😊

**Comment by tidupls** [comment]
Will hopefully start this weekend :+1:

**Comment by egoist** [comment]
That sounds awesome 👊

**Comment by maximilienGilet** [comment]
About to start working on a Darcula and Monokai theme, what do you think about ?

**Comment by jhabdas** [comment]
@maximilienGilet Monokai is very popular. I'm also a big fan of the _One Dark_ theme in Atom. Either of the two would help satisfy the ask in #21.

**Comment by jhabdas** [comment]
Shelving this due to inactivity.
