### ISSUE TITLE
bower installation issues

### ISSUE THREAD

**Issue by sobolevn** [egoist/hack#25]
When installing from `bower` there's an issue with `color-preset`.

Here's the output (I am using `brunch`):

> 11 Aug 17:28:50 - error: Compiling of web/static/scss/main.scss failed. File to import not found or unreadable: color-preset
> Parent style sheet: bower_components/hackcss/src/css/hack.css

Looks like `bower.json` is missing this library as a dependency. But [it is presented](https://github.com/egoist/hack/blob/c898f22207eb8ef7cd5318b94d0a666c395d2380/package.json#L33) in `package.json`.

**Comment by egoist** [comment]
You should import 'dist/hack.css' instead

**Comment by sobolevn** [comment]
There's no `dist` folder by default. Should I build it with `gulp`?
<img width="183" alt="2016-08-11 20 01 15" src="https://cloud.githubusercontent.com/assets/4660275/17597494/b75feb7a-5ffe-11e6-887e-888f504b1cf6.png">

**Comment by egoist** [comment]
oh i guess i did it wrong, dist is not included in git, I can fix it later,

for now you can use `npm install hack`

**Comment by egoist** [comment]
I think I'd use @kentcdodds 's [solution](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564#.ukx29bvmo) instead

**Comment by egoist** [comment]
I would remove bower support, since you have bower installed you also have npm installed, so why not `npm install hack` instead?

**Comment by sobolevn** [comment]
I really like to separate these two: `npm` is for complex dependencies (`gulp`, `gulp-tasks`, `bower` itself), `bower` is for frontend only.

**Comment by egoist** [comment]
for what reason?

**Comment by sobolevn** [comment]
basically just because of how the dependencies are resolved. `bower` keeps them flat. so when installing multiple modules that require different versions of `jQuery` to work you will run into dependency resolution errors early. 

it is also easier to navigate, since `node_modules` always has a lot of packages.

**Comment by jhabdas** [comment]
@sobolevn Paul Miller and team added NPM support to brunch. I'd advise switching.

**Comment by jhabdas** [comment]
@sobolevn is this still an issue? if not, would you mind closing it?
