### ISSUE TITLE
permanent link icon

### ISSUE THREAD

**Issue by sobolevn** [egoist/hack#26]
Github has this feature. And I really like it.

<img width="339" alt="2016-08-12 0 32 18" src="https://cloud.githubusercontent.com/assets/4660275/17605712/78423dbe-6024-11e6-9b29-0df4fe4ce52b.png">

How does it suppose to work? I suggest to add an extra class (something like `permanent`), which would add an icon on `hover`.

Something like this:
<img width="221" alt="2016-08-12 0 32 25" src="https://cloud.githubusercontent.com/assets/4660275/17605747/9e819c18-6024-11e6-985d-b050964f1598.png">

**Comment by jhabdas** [comment]
-1 @sobolevn I think you're looking for http://bryanbraun.github.io/anchorjs/

**Comment by ahmadnassri** [comment]
agreed with @jhabdas

**Comment by jhabdas** [comment]
@egoist can this be closed now?
