### ISSUE TITLE
`a.btn` clashes with other elements

### ISSUE THREAD

**Issue by sobolevn** [egoist/hack#27]
## Problem

I have created a [codepen](http://codepen.io/anon/pen/WxLqwP) with the error.

Duplicating it here just in case:

```html
<body class="hack">
  <a class="btn btn-primary btn-ghost" href="#some">Register</a>

  <h2>Recent events</h2>
</body>
```

Will result in:
<img width="178" alt="2016-08-12 11 11 19" src="https://cloud.githubusercontent.com/assets/4660275/17616737/c2ff8f50-607e-11e6-9d28-04175b3db501.png">

## Solution

I suggest to add this rule: `.btn { display: inline-block; }`, because that's the way `button` element renders. 

If that's fine I will send a PR.

**Comment by egoist** [comment]
sure thing, i think it's fine, just do a PR 😊
