### ISSUE TITLE
Modal support

### ISSUE THREAD

**Issue by maximilienGilet** [egoist/hack#29]
How about adding a modal element ?

**Comment by frenchbread** [comment]
+1

**Comment by jhabdas** [comment]
http://devdocs.io/dom/htmldialogelement

**Comment by jhabdas** [comment]
For those who are looking for something a little fancier in the modal department I've had great success using `hackcss` alongside http://photoswipe.com/.

The benefit here is it helps keep hackcss lean and mean and enables authors to provide their own idea of what a modal should be.

Closing this as there hasn't been much traction in over a year and there are both standards-based and JS based alternatives which better adhere to the linux philosophy.
