### ISSUE TITLE
Small screen/responsive issue

### ISSUE THREAD

**Issue by brainsiq** [egoist/hack#34]
Awesome job on this library :+1: 

I don't know CSS so well so not sure why this is happening but if you look at my site http://chris.impey.io you will see the grid at the top seems to be nicely responsive (if you make your browser smaller the image drops away nicely) but if you look at it on a phone/small screen (or use device emulation in dev tools) then the content in the grid is tiny and the image always displays.

**Comment by egoist** [comment]
try adding the following code into the html head:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by brainsiq** [comment]
That did the job, thanks very much!
