### ISSUE TITLE
[Suggestion] Add `normalize.css`

### ISSUE THREAD

**Issue by sobolevn** [egoist/hack#35]
I have faced several issues with normalizing different elements across multiple platforms and browsers.

It is a normal practice to use `css` resets. Such as [`nomalize.css`](https://necolas.github.io/normalize.css/) or any other.

What do you think?

**Comment by Suriteka** [comment]
I think it's a good idea. Normalize is great.
But the [MeyerWeb](http://meyerweb.com/eric/tools/css/reset/) snippet too.

**Comment by egoist** [comment]
nomalize.css is great, but bundle all things in one sounds not that good to me, it makes the library less modular and extendable.

**Comment by toh82** [comment]
normalize css should not be integrated, IMHO. It's available as npm module (https://www.npmjs.com/package/normalize-css), just put it into your project.

**Comment by jhabdas** [comment]
Agreed with @toh82. Closing.
