### ISSUE TITLE
Add hack to jsDelivr.

### ISSUE THREAD

**Issue by NurdTurd** [egoist/hack#37]
Please! I understand that you have npmcdn links but jsDelivr is so much better!

**Comment by egoist** [comment]
it's also in https://cdnjs.com/libraries/hack

**Comment by NurdTurd** [comment]
I understand that but jsDelivr is a lot better. The latency is better plus it has Multi-CDN support.

**Comment by jhabdas** [comment]
This library is so compact and awesome I just inlined it in the `head` to prevent the FOUC. Thanks for the great work!

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by jhabdas** [comment]
@egoist This is a great opportunity IMO to host this library on CDN. Adding a library to jsDelivr is fairly simple. Here's an example of a JS library I created being added to jsDelivr:

https://github.com/jsdelivr/jsdelivr/pull/16851

Besides HTTP/2 stuff, jsDelivr also allows individuals to create bundles dynamically. And best of all the entire system is open source and automated.

See the jsDelivr readme for more details: https://github.com/jsdelivr/jsdelivr/

**Comment by jimaek** [comment]
@jhabdas Hey, all this is no longer needed.  We pull files from npm automatically.
Here is an example http://cdn.jsdelivr.net/npm/hack@0.8.0/dist/

**Comment by jhabdas** [comment]
@jimaek sweet business! @egoist this issue can be closed /cc @NurdTurd

**Comment by egoist** [comment]
@jimaek So good! I definitely would use jsDelivr more just because of this feature 👏

**Comment by NurdTurd** [comment]
@jimaek Right, but their backend doesn't support HTTPS currently.

**Comment by jhabdas** [comment]
Interesting. Potential Man in the Middle

**Comment by jhabdas** [comment]
please ignore my reply to the deleted comment. I'm not here to spread fud

**Comment by jhabdas** [comment]
@egoist I may have given a bad recommendation after seeing the follow-up response from @jimaek. I just checked here and don't see hack listed: http://www.jsdelivr.com/?query=hack

**Comment by jimaek** [comment]
We plan to update the site this month. Its not simple because we will basically list everything https://www.npmjs.com/ lists since we support all npm packages. Until then just create the URLs manually. 

You can link here instead if you want http://cdn.jsdelivr.net/npm/hack/
