### ISSUE TITLE
icons recommendation

### ISSUE THREAD

**Issue by sobolevn** [egoist/hack#42]
Which set of icons should be the recommended one? Since there are a lot of them: http://fontello.com/ , https://css-tricks.com/flat-icons-icon-fonts/ and many others.

For my taste `font-awesome` does not fit here.

**Comment by jhabdas** [comment]
@sobolevn have you looked at evil icons? those might fit well. otherwise you can get more ideas here: https://github.com/oblador/react-native-vector-icons/

**Comment by egoist** [comment]
Personally I use https://github.com/danklammer/bytesize-icons

**Comment by jhabdas** [comment]
@egoist purrfect!

**Comment by jhabdas** [comment]
Closing as the recommendation has been made. I've left some samples of using the icon set suggested by @egoist in the Hugo hack theme.
