### ISSUE TITLE
Add dotted underline for ABBR tag

### ISSUE THREAD

**Issue by jhabdas** [egoist/hack#43]
For better accessibility, it would be nice to have a dotted underline the same color as the theme link for the `abbr` element, as shown here in its current form:

<img width="152" alt="screen shot 2016-10-02 at 7 40 03 am" src="https://cloud.githubusercontent.com/assets/440298/19020661/0271ea98-8875-11e6-88f4-d83b423ff29d.png">

**Comment by egoist** [comment]
Sure, PR welcome, that should a `border-bottom: 1px solid;` thing

**Comment by jhabdas** [comment]
My user agent adds `text-underline: underline dotted` as expected for `abbr[title]` so not sure this is a valid issue. Closing.
