### ISSUE TITLE
Whitespace in nested lists

### ISSUE THREAD

**Issue by jhabdas** [egoist/hack#48]
Thoughts on tightening up nested lists in the base themes? Here's an example of a table of contents with and without whitespace adjustments:

Current output (top and bottom margins on `li ul`):

<img width="422" alt="screen shot 2017-02-04 at 5 04 50 pm" src="https://cloud.githubusercontent.com/assets/440298/22617293/18334f2c-eafc-11e6-8212-564e6eaab542.png">

Tightened output (without top and bottom margins on `li ul`):

<img width="400" alt="screen shot 2017-02-04 at 4 53 35 pm" src="https://cloud.githubusercontent.com/assets/440298/22617288/014a5a4e-eafc-11e6-8af6-868df3486e28.png">

The markup pattern for the above list is auto-generated by Hugo as:

```html
<nav id="TableOfContents">
<ul>
<li><a href="#deciding-if-bali-is-right-for-you">Deciding if Bali is right for you</a></li>
<li><a href="#move-considerations">Move considerations</a>
<ul>
<li><a href="#relative-costs">Relative costs</a></li>
</ul></li>
<li><a href="#making-the-move">Making the move</a>
<ul>
<li><a href="#shedding-the-weight">Shedding the weight</a>
<ul>
<li><a href="#furry-friends">Furry friends</a></li>
<li><a href="#selling-your-stuff">Selling your stuff</a></li>
</ul></li>
<li><a href="#tying-up-loose-ends">Tying up loose ends</a></li>
<li><a href="#making-a-soft-landing">Making a soft landing</a>
<ul>
<li><a href="#finding-a-place-to-stay">Finding a place to stay</a></li>
<li><a href="#securing-travel-insurance">Securing travel insurance</a></li>
<li><a href="#attracting-a-partner">Attracting a partner</a></li>
<li><a href="#getting-questions-answered">Getting questions answered</a></li>
</ul></li>
</ul></li>
<li><a href="#settling-in">Settling in</a>
<ul>
<li><a href="#get-your-visa-on-arrival">Get your Visa On Arrival</a></li>
<li><a href="#get-some-cash">Get some cash</a></li>
<li><a href="#purchase-necessities">Purchase necessities</a></li>
<li><a href="#get-a-bank-account">Get a bank account</a></li>
<li><a href="#switch-mobile-carriers">Switch mobile carriers</a></li>
<li><a href="#getting-around">Getting around</a></li>
<li><a href="#where-to-work">Where to work</a></li>
<li><a href="#where-to-eat">Where to eat</a></li>
<li><a href="#addressing-language-barriers">Addressing language barriers</a></li>
</ul></li>
<li><a href="#wrapping-up">Wrapping up</a></li>
</ul>
</nav>
```

**Comment by maximilienGilet** [comment]
Looks good, why not making a class like `compact`or `list-compact` on the `ul` element ?

**Comment by jhabdas** [comment]
@maximilienGilet seems logical. not sure what @egoist wants to do direction-wise Re: supporting variants. But damn this theme looks slick when put in action:

http://hackcabin.com/post/become-digital-nomad-bali/

**Comment by egoist** [comment]
I guess we can directly override `ul` `ol` 's default style.

**Comment by jhabdas** [comment]
Closing this as it's easy enough to override. The issue's here in case someone wants to sub a PR in the future. Trying to keep the repo clean.
