### ISSUE TITLE
Blockquotes

### ISSUE THREAD

**Issue by Fastidious** [egoist/hack#49]
I think the way <`blockquotes>` are currently handled isn’t pretty. Could they be made like so?

```
> This is the beginning of the blockquote.
> This is the next line, and,
> This is the last.
```

**Comment by jhabdas** [comment]
@Fastidious Looking at the hack.css docs that's exactly how they're handled. If there's a nested `p` tag they'll also receive an extra `>` at the top and bottom, like:

<img width="376" alt="screen shot 2017-02-19 at 4 15 05 pm" src="https://cloud.githubusercontent.com/assets/440298/23100531/a118a5f8-f6be-11e6-90ca-1da1b86d14ae.png">

Aside, if you're looking for more powerful way to display blockquotes in Hugo try this custom shortcode:

```
<blockquote {{ with .Get "class" }}class="{{ . }}"{{ end }} {{ with .Get "citelink" }}cite="{{ . }}"{{ end }}>
  {{ .Inner }}
  {{ with .Get "citelink" }}
    <cite><a href="{{ . }}">{{ $.Get "cite" }}</a></cite>
  {{ else }}
    <cite>{{ .Get "cite" }}</cite>
  {{ end }}
</blockquote>
```

And use it like this:

```
{{< blockquote cite="BeCandid.com/faq" citelink="https://becandid.com/faq" >}}
  <p>Candid’s AI is improving all the time, and your reports help keep the service safe.</p>
{{< /blockquote >}}
```

@egoist I believe this can be closed.

**Comment by Fastidious** [comment]
@jhabdas I ended up overwriting element to remove the greater than signs. It was a less convoluted approach.
