### ISSUE TITLE
Ordered lists >=10 not properly aligned

### ISSUE THREAD

**Issue by Fastidious** [egoist/hack#51]
Numbered lists with more than nine will miss the dot (actually, the dot will overlap the text on the line).

**Comment by jhabdas** [comment]
<img width="79" alt="screen shot 2017-02-19 at 4 21 52 pm" src="https://cloud.githubusercontent.com/assets/440298/23100567/919f033c-f6bf-11e6-8c7a-1d877445c6f0.png">

**Comment by jhabdas** [comment]
@Fastidious what are your thoughts on list sizes > 100?

**Comment by Fastidious** [comment]
@jhabdas yeah, same problem, or worse. Having numbered lists that go into the hundreds, or thousands, is extremely rare though, and might be hard to account for.

**Comment by jhabdas** [comment]
Thanks. Whatever the case may be, this problem should already be solved by CSS, so I can look into a fix for this. If it's not solved by CSS then it's not really an issue for this repo. More info to follow.
