### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by jhabdas** [egoist/hack#54]
I see the versions rolling forward, but I cannot easily make sense of what's changing. Providing a ChangeLog will help consumers of this library understand what's changing between versions from a simple text file. Here's an example ChangeLog:

https://github.com/comfusion/after-dark/blob/master/CHANGELOG.md

And here's how to accomplish it with some super simple tooling:

https://github.com/comfusion/after-dark/blob/master/package.json#L17
https://github.com/comfusion/after-dark/blob/master/package.json#L25-L27

Using this approach your entire release workflow (with ChangeLogs, tagging and publishing) ends up looking like this:

1. `npm run release`
1. (copy/paste resulting script output, and execute it)

**Comment by jhabdas** [comment]
@egoist if you're up for it I'll send in a pull for this.

**Comment by egoist** [comment]
Hmm I don't want to use a strict commit message convention, maybe https://github.com/zeit/release or https://github.com/egoist/changelog.md instead

**Comment by jhabdas** [comment]
You've got your own. Love it! Could dogfood it here. I'd be glad to offer feedback. For Zeit, I'll plan on on a project with multiple contributors to form an opinion.

**Comment by egoist** [comment]
btw If you're insterested I can add you to the repo since I don't really have much time to add new features.

**Comment by jhabdas** [comment]
Sign me up

**Comment by jhabdas** [comment]
I'm in. I'll plan on fixes for now, and later will look to add features only where it meets the Pareto principle. Pick a ChangeLog and and I'll work it into the system as I squash some bugs.

**Comment by jhabdas** [comment]
Closing this due to age. Please feel free to re-open.
